SELECT SUB_FF.FACTORY_ID,
       SUB_FF.FACTORY_NAME,
       SUB_FF.ADDRESS
FROM (
     SELECT SUBSTRING_INDEX(FF.ADDRESS,' ',1) AS SI_ADDRESS,
            FF.FACTORY_ID,
            FF.FACTORY_NAME,
            FF.ADDRESS
     FROM FOOD_FACTORY AS FF
) AS SUB_FF
WHERE 1 = 1
 AND SUB_FF.SI_ADDRESS = '강원도'
 ORDER BY FACTORY_ID ASC;