SELECT PT.PT_NAME,
       PT.PT_NO,
       PT.GEND_CD,
       PT.AGE,
       IFNULL(PT.TLNO,'NONE') AS TLNO
FROM PATIENT AS PT
WHERE 1 = 1
 AND PT.AGE <= 12
 AND PT.GEND_CD = 'W'
 ORDER BY PT.AGE DESC, PT.PT_NAME ASC;