SELECT DC.DR_NAME,
       DC.DR_ID,
       DC.MCDP_CD,
       DATE_FORMAT(DC.HIRE_YMD,'%Y-%m-%d') AS HIRE_YMD
FROM DOCTOR AS DC
WHERE 1 = 1
 AND DC.MCDP_CD IN ('CS','GS')
ORDER BY DC.HIRE_YMD DESC, DC.DR_NAME ASC;