-- TODO 날짜기간이라는 단어가 좀 이상한데, 해당 부분은 다시 확인해봐야 할 필요가 잇음
SELECT CRCRH.HISTORY_ID,
       CRCRH.CAR_ID,
       DATE_FORMAT(CRCRH.START_DATE,'%Y-%m-%d') AS START_DATE,
       DATE_FORMAT(CRCRH.END_DATE,'%Y-%m-%d') AS END_DATE,
        CASE WHEN DATEDIFF(END_DATE, START_DATE) >= 29 then '장기 대여'
            ELSE '단기 대여'
            END AS  RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CRCRH
WHERE 1 = 1
 AND DATE_FORMAT(CRCRH.START_DATE,'%Y-%m') = '2022-09'
ORDER BY CRCRH.HISTORY_ID DESC;