SELECT B.BOOK_ID ,
       DATE_FORMAT(B.PUBLISHED_DATE,'%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK AS B
WHERE 1 = 1
 AND B.CATEGORY = '인문'
 AND DATE_FORMAT(B.PUBLISHED_DATE,'%Y') = '2021'
ORDER BY B.PUBLISHED_DATE ASC;